stages:
  - build_envs
  - lint
  - sanity
  - build
  - package
  - publish

include:
   - '.gitlab-ci/lint.yml'
   - '.gitlab-ci/sanity.yml'
   - '.gitlab-ci/build_packages.yml'
   - '.gitlab-ci/publish.yml'
   - '.gitlab-ci/containers.yml'
   - '.gitlab-ci/pages.yml'
