build_archlinux:
  stage: package
  parallel:
    matrix:
      - RUNNER_TAG: [archlinux]
  before_script:
    - |
      if [ ! -f /usr/bin/make ]; then
        sudo pacman -Sy make;
      fi;
      if [ ! -f /usr/bin/cmake ]; then
        sudo pacman -Sy cmake;
      fi;
      if [ ! -d "packages" ]; then
         mkdir -p packages/archlinux/x86_64
      fi;
  script:
    - |
      ARTIFACTDIR="${PWD}/packages/archlinux/x86_64";
      cd processmanagment/os/c_cpp;
      if [ -n "${CI_PIPELINE_IID}" ]; then
        make BUILD_ID=${CI_PIPELINE_IID} -f Makefile_packages update_version;
      fi;
      echo "[INFO] Copy packages to ${ARTIFACTDIR}";
      make -f Makefile_packages swtrprocmgtutils_create_distro
      find ARCHLINUXBUILD -name "*.tar.zst" -exec cp {} "${ARTIFACTDIR}" \;
      rm -r -f ARCHLINUXBUILD/*;
      make BUILD_ID=${CI_PIPELINE_IID} SWTRPROCMGTUTILS_CURPKG=swtrprocmgtutils -f Makefile_packages swtrprocmgtutils_create_distro
      find ARCHLINUXBUILD -name "*.tar.zst" -exec cp {} "${ARTIFACTDIR}" \;
      rm -r -f ARCHLINUXBUILD/*;
      make BUILD_ID=${CI_PIPELINE_IID} SWTRPROCMGTUTILS_CURPKG=swtrprocmgtlib -f Makefile_packages swtrprocmgtutils_create_distro
      find ARCHLINUXBUILD -name "*.tar.zst" -exec cp {} "${ARTIFACTDIR}" \;
      rm -r -f ARCHLINUXBUILD/*;
      make BUILD_ID=${CI_PIPELINE_IID} SWTRPROCMGTUTILS_CURPKG=swtrstrlib -f Makefile_packages swtrprocmgtutils_create_distro
      find ARCHLINUXBUILD -name "*.tar.zst" -exec cp {} "${ARTIFACTDIR}" \;
      rm -r -f ARCHLINUXBUILD/*;
      make BUILD_ID=${CI_PIPELINE_IID} SWTRPROCMGTUTILS_CURPKG=swtrprocmgtlib -f Makefile_packages swtrprocmgtutils_create_distro
      find ARCHLINUXBUILD -name "*x86_64.tar.zst" -exec cp {} "${ARTIFACTDIR}" \;
      echo "[INFO] list packages in ${ARTIFACTDIR}";
      ls -l "${ARTIFACTDIR}";
  needs: ["sanity"]
  tags:
    - $RUNNER_TAG
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - changes:
         - .gitlab-ci.yml
         - .gitlab-ci/*.yml
         - ./processmanagement/os/c_cpp/**/Makefile
         - ./processmanagement/os/c_cpp/**/*.mk
         - ./processmanagement/os/c_cpp/**/*.h
         - ./processmanagement/os/c_cpp/**/*.c
  artifacts:
    paths:
      - packages/archlinux/x86_64/

build_archlinux_container:
  stage: package
  image: gitlab01.brunoe.net:5050/ebruno/softwaretrace-ostools/archlinuxbuild:latest
  parallel:
    matrix:
      - RUNNER_TAG: [fedoracontainers,debcontainer]
  before_script:
    -|
      which make;
      which cmake;
      which makepkg;

  script:
    -|
      echo "test of contents"
      ls -l;
  needs: ["sanity"]
  tags:
    - $RUNNER_TAG
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - changes:
         - .gitlab-ci.yml
         - .gitlab-ci/*.yml
         - ./processmanagement/os/c_cpp/**/Makefile
         - ./processmanagement/os/c_cpp/**/*.mk
         - ./processmanagement/os/c_cpp/**/*.h
         - ./processmanagement/os/c_cpp/**/*.c
  artifacts:
    paths:
      - packages/archlinux/x86_64/
