container:
  stage: build_envs
  parallel:
    matrix:
      - RUNNER_TAG: [debian]
  script:
    - |
       env | grep CI | sort;
  allow_failure:
    exit_codes:
      - 1

  tags:
     - $RUNNER_TAG

  rules:
    - if: $CI_SWTR_ONLY_CONTAINERS == "true"
      when: on_success
    - changes:
         - .gitlab-ci.yml
         - .gitlab-ci/containers.yml
         - ./system_management/build_containers/**/Containerfile
         - ./system_management/build_containers/**/Doxyfile
         - ./system_management/build_containers/packages/*
      when: on_success
    - when: never
