container:
  stage: build_envs
  parallel:
    matrix:
      - RUNNER_TAG: [debian]
  before_script:
    - |
     echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

  script:
    - |
      if [ -x /usr/bin/podman ]; then
        PODMAN="podman";
      fi;
      if [ -x /usr/bin/docker ]; then
          DOCKER="docker";
      fi;
      if [ -n "${PODMAN}" ]; then
         CONTAINER_APP="${PODMAN}";
      elif [ -n "${DOCKER}" ]; then
         CONTAINER_APP="${DOCKER}";
      else
        echo "[ERROR] podman or docker not present in environment."
        exit 1;
      fi;
      #${CONTAINER_APP} build -t gitlab01.brunoe.net:5050/ebruno/softwaretrace-ostools/rhel10rpmbuild -t rhel10rpmbuild -f rhel10/Containerfile;
      cd build_containers;
      ${CONTAINER_APP} build -t ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE_SLUG}/${CI_PROJECT_NAME}/rhel10rpmbuild -t rhel10rpmbuild -f rhel10/Containerfile;
      ${CONTAINER_APP} images;

  tags:
     - $RUNNER_TAG

  rules:
    - if: $CI_SWTR_ONLY_CONTAINERS == "true"
      when: on_success
    - changes:
         - .gitlab-ci.yml
         - .gitlab-ci/containers.yml
         - ./system_management/build_containers/**/Containerfile
         - ./system_management/build_containers/**/Doxyfile
         - ./system_management/build_containers/packages/*
      when: on_success
    - when: never
