clear_tmp_enable="YES"
hostname="shuttle01.sc.brunoe.net"
keymap="us.kbd"
ifconfig_ix0="DHCP"
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
kld_list="i915kms"
sddm_enable="YES"
seatd_enable="YES"
dbus_enable="YES"
gitlab_runner_enable="YES"
jail_enable="YES"
jail_parallel_start="YES"
cupsd_enable="YES"
devfs_system_ruleset="system"
lpd_enable="YES"
avahi_daemon_enable="YES"  # For automatic printer discovery
nfs_client_enable="YES"
rpc_lockd_enable="YES"
rpc_statd_enable="YES"
autofs_enable="YES"
rpcbind_enable="YES"
