
SWTRPROCMGTUTILS_NAME           = swtrprocmgtutils

SWTRPROCMGTUTILS_MAJOR          = 0

SWTRPROCMGTUTILS_MINOR          = 9

SWTRPROCMGTUTILS_SUBVERSION     = 0

SWTRPROCMGTUTILS_PRIVATE_BUILD_ID     = 0

SWTRPROCMGTUTILS_BUILD_NUMBER     = 2

SWTRPROCMGTUTILS_RELEASE_KEY     = 0


#swtrprocmgtutils_0.9.0.0.2.orig.tar.gz
SWTRPROCMGTUTILS_TARFILE_NAME   = ${SWTRPROCMGTUTILS_NAME}-${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}.${SWTRPROCMGTUTILS_PRIVATE_BUILD_ID}.${SWTRPROCMGTUTILS_BUILD_NUMBER}.tar.gz

SWTRPROCMGTUTILS_SRCDIR_NAME   = ${SWTRPROCMGTUTILS_NAME}-${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}.${SWTRPROCMGTUTILS_PRIVATE_BUILD_ID}.${SWTRPROCMGTUTILS_BUILD_NUMBER}

SWTRPROCMGTUTILS_ARCHLINUX_BUILDDIRS = sources srcpackages packages logs

SWTRCOMMON_FILES          = CMakeLists.txt Makefile_packages Makefile_doc
SWTRPROCMGTUTILS_DOC_FILES 	  = 
SWTRPROCMGTUTILS_LICENSE_FILES  = ../../../LICENSE
SWTRPROCMGTUTILS_FILES          = make_swtrprocmgtutils_archlinux.mk
SWTRPROCMGTUTILS_DIRS           = src_c

SWTRPROCMGUTILS_CHANGE_LOG = ChangeLog_archlinux

swtrprocmgtutils_all:
		@echo "dummy_all"
		@exit 0;

swtrprocmgtutils_create_distro: swtrprocmgtutils_create_buildarea swtrprocmgtutils_create_changelog swtrprocmgtutils_create_src swtrprocmgtutils_create_pkg

swtrprocmgtutils_create_buildarea:
	@if ! test -d ${PACMANBUILD_BASE}; then \
               $(foreach item,${SWTRPROCMGTUTILS_ARCHLINUX_BUILDDIRS}, mkdir -p ${PACMANBUILD_BASE}/${item};) \
	fi;

swtrprocmgtutils_create_src: swtrprocmgtutils_create_buildarea
	@echo "Creating Source Distribution ${SWTRPROCMGTUTILS_TARFILE_NAME}";
	@if test -d "${SWTRPROCMGTUTILS_NAME}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; then \
	   rm -r -f "${SWTRPROCMGTUTILS_NAME}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; \
	fi;
	@mkdir -p "${SWTRPROCMGTUTILS_SRCDIR_NAME}";
	@$(foreach item, ${SWTRCOMMON_FILES} ${SWTRPROCMGTUTILS_FILES} ${SWTRPROCMGTUTILS_DOC_FILES} ${SWTRPROCMGTUTILS_LICENSE_FILES},cp -p ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@$(foreach item, ${SWTRPROCMGTUTILS_DIRS}, cp -r ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@if test -d "${SWTRPROCMGTUTILS_NAME}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; then \
	   rm -r -f "${SWTRPROCMGTUTILS_NAME}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; \
	fi;
	@mkdir -p "${SWTRPROCMGTUTILS_SRCDIR_NAME}";
	@$(foreach item, ${SWTRCOMMON_FILES} ${SWTRPROCMGTUTILS_FILES} ${SWTRPROCMGTUTILS_DOC_FILES},cp -p ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@$(foreach item, ${SWTRPROCMGTUTILS_DIRS}, cp -r ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@if ! test -d ${ARCLINUX_SOURCE_DIR}; then \
	   echo "Creating ${ARCLINUX_SOURCE_DIR}"; \
	   mkdir -p ${ARCLINUX_SOURCE_DIR}; \
	fi;
	@tar -czf ${ARCLINUX_SOURCE_DIR}/${SWTRPROCMGTUTILS_TARFILE_NAME} "${SWTRPROCMGTUTILS_SRCDIR_NAME}"
	@rm -r -f "${SWTRPROCMGTUTILS_SRCDIR_NAME}";

swtrprocmgtutils_create_changelog:
			cp ${SWTRPROCMGUTILS_CHANGE_LOG} ${PACMANBUILD_BASE}/ChangeLog

swtrprocmgtutils_create_pkg: swtrprocmgtutils_create_buildarea swtrprocmgtutils_create_changelog
		@cp archpkg_templates/PKGBUILD_${SWTRPROCMGTUTILS_NAME}.proto ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XMAJOR/${SWTRPROCMGTUTILS_MAJOR}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XMINOR/${SWTRPROCMGTUTILS_MINOR}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XSUBVERSION/${SWTRPROCMGTUTILS_SUBVERSION}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XPRIVATE_BUILD_ID/${SWTRPROCMGTUTILS_PRIVATE_BUILD_ID}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XBUILD_NUMBER/${SWTRPROCMGTUTILS_BUILD_NUMBER}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@if ! test -d ${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}; then \
		   rm -f ${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}/${SWTRPROCMGTUTILS_NAME}*.tar.xz; \
		fi;
		@echo "Update checksums";
	        @export PKGDEST="${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}"; \
		export BUILDDIR="${PACMANBUILD_BASE}"; \
		export SRCDEST="${PACMANBUILD_BASE}/sources"; \
		export SRCPKGDEST="${PACMANBUILD_BASE}/srcpackages"; \
		export LOGDEST="${PACMANBUILD_BASE}/logs"; \
		export PACKAGER="Eric Bruno <eric@ebruno.org>"; \
		cd ${PACMANBUILD_BASE}; pwd; \
		makepkg -g >> ${PACMANBUILD_BASE}/PKGBUILD; \
	        export PKGDEST="${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}"; \
		export BUILDDIR="${PACMANBUILD_BASE}"; \
		export SRCDEST="${PACMANBUILD_BASE}/sources"; \
		export SRCPKGDEST="${PACMANBUILD_BASE}/srcpackages"; \
		export LOGDEST="${PACMANBUILD_BASE}/logs"; \
		export PACKAGER="Eric Bruno <eric@ebruno.org>"; \
		makepkg -C ${SWTRPROCMGTUTILS_PACMAN_OVERRIDE} updpkgsums

