
SWTRPROCMGTUTILSLIB_NAME           = swtrprocmgtutils

SWTRPROCMGTUTILSLIB_MAJOR          = 0

SWTRPROCMGTUTILSLIB_MINOR          = 9

SWTRPROCMGTUTILSLIB_SUBVERSION     = 0

SWTRPROCMGTUTILSLIB_PRIVATE_BUILD_ID     = 0

SWTRPROCMGTUTILSLIB_BUILD_NUMBER     = 2

SWTRPROCMGTUTILSLIB_RELEASE_KEY     = 0

SWTRPROCMGTUTILSLIB_TARFILE_NAME   = ${TARFILE_NAME}-${SWTRPROCMGTUTILSLIB_MAJOR}.${SWTRPROCMGTUTILSLIB_MINOR}.${SWTRPROCMGTUTILSLIB_SUBVERSION}.${SWTRPROCMGTUTILSLIB_PRIVATE_BUILD_ID}.${SWTRPROCMGTUTILSLIB_BUILD_NUMBER}.tar.gz

SWTRPROCMGTUTILSLIB_SRCDIR_NAME   = ${SWTRPROCMGTUTILSLIB_NAME}-${SWTRPROCMGTUTILSLIB_MAJOR}.${SWTRPROCMGTUTILSLIB_MINOR}.${SWTRPROCMGTUTILSLIB_SUBVERSION}.${SWTRPROCMGTUTILSLIB_PRIVATE_BUILD_ID}.${SWTRPROCMGTUTILSLIB_BUILD_NUMBER}

SWTRCOMMON_FILES          = CMakeLists.txt Makefile_packages Makefile_doc
SWTRPROCMGTUTILSLIB_DOC_FILES 	  = 
SWTRPROCMGTUTILSLIB_FILES          = make_swtrstrlib_rpm.mk
SWTRPROCMGTUTILSLIB_DIRS           = src_c


swtrprocmgtutilslib_create_src:
	@echo "Creating Source Distribution ${SWTRPROCMGTUTILSLIB_TARFILE_NAME}";
	@if test -d "${SWTRPROCMGTUTILSLIB_NAME}.${SWTRPROCMGTUTILSLIB_MAJOR}.${SWTRPROCMGTUTILSLIB_MINOR}.${SWTRPROCMGTUTILSLIB_SUBVERSION}"; then \
	   rm -r -f "${SWTRPROCMGTUTILSLIB_NAME}.${SWTRPROCMGTUTILSLIB_MAJOR}.${SWTRPROCMGTUTILSLIB_MINOR}.${SWTRPROCMGTUTILSLIB_SUBVERSION}"; \
	fi;
	@mkdir -p "${SWTRPROCMGTUTILSLIB_SRCDIR_NAME}";
	@$(foreach item, ${SWTRCOMMON_FILES} ${SWTRPROCMGTUTILSLIB_FILES} ${SWTRPROCMGTUTILSLIB_DOC_FILES},cp -p ${item} ${SWTRPROCMGTUTILSLIB_SRCDIR_NAME};)
	@$(foreach item, ${SWTRPROCMGTUTILSLIB_DIRS}, cp -r ${item} ${SWTRPROCMGTUTILSLIB_SRCDIR_NAME};)
	@tar -czf ${RPMBUILD_SOURCE_DIR}/${SWTRPROCMGTUTILSLIB_TARFILE_NAME} "${SWTRPROCMGTUTILSLIB_SRCDIR_NAME}"
	@rm -r -f "${SWTRPROCMGTUTILSLIB_SRCDIR_NAME}";

swtrprocmgtutilslib_create_rpm: swtrprocmgtutilslib_create_src
	@if ! test -d ${CURDIR}/${SPEC_DIR}; then \
		mkdir -p ${CURDIR}/${SPEC_DIR}; \
	fi;
	@if test -d ${CURDIR}/${SPEC_TEMPLATE_DIR}; then \
		cat ${SPEC_TEMPLATE_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec.tmpl | sed -e "s/XMAJOR/${SWTRPROCMGTUTILSLIB_MAJOR}/g" > ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec; \
		sed -e "s/XMINOR/${SWTRPROCMGTUTILSLIB_MINOR}/g" -i ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec;\
		sed -e "s/XSUBVERSION/${SWTRPROCMGTUTILSLIB_SUBVERSION}/g" -i ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec;\
		sed -e "s/XPRIVATE_BUILD_ID/${SWTRPROCMGTUTILSLIB_PRIVATE_BUILD_ID}/g" -i ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec;\
		sed -e "s/XBUILD_NUMBER/${SWTRPROCMGTUTILSLIB_BUILD_NUMBER}/g" -i ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec;\
		sed -e "s/XRELEASE_KEY/${SWTRPROCMGTUTILSLIB_RELEASE_KEY}/g" -i ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec;\
		rpmbuild ${RPM_VERBOSE} -bb ${SPEC_DIR}/${SWTRPROCMGTUTILSLIB_NAME}.spec; \
	else \
	  echo "Error unable to locate ${CURDIR}/${SPEC_TEMPLATE_DIR}, fatal,terminating"; \
	  exit 1; \
	fi;

