SWTRPROCMGTDEMO_NAME            = swtrprocmgtdemo

SWTRPROCMGTUTILS_NAME           = swtrprocmgtutils

SWTRSTRLIB_NAME			= swtrstrlib

SWTRPROCMGTLIB_NAME             = swtrprocmgtlib

ifeq ($(strip $(SWTRPROCMGTUTILS_CURPKG)),)
	SWTRPROCMGTUTILS_CURPKG  = $(SWTRPROCMGTDEMO_NAME)
endif
VERSION_FILE	=	version.mk
ifeq (,$(wildcard $(VERSION_FILE)))
MAJOR = 0
MINOR = 9
SUBVERSION = 5
BUILD_NUM = 2
PRIVATE_BUILD_ID=0
else
include version.mk
BUILD_NUM=$(BUILD_ID)
endif

SWTRPROCMGTUTILS_MAJOR			= $(MAJOR)
SWTRPROCMGTUTILS_MINOR			= $(MINOR)
SWTRPROCMGTUTILS_SUBVERSION		= $(SUBVERSION)
SWTRPROCMGTUTILS_PRIVATE_BUILD_ID	= $(PRIVATE_BUILD_ID)
SWTRPROCMGTUTILS_BUILD_NUMBER		= $(BUILD_NUM)
SWTRPROCMGTUTILS_RELEASE_KEY		= 0


#swtrprocmgtutils_0.9.0.0.2.orig.tar.gz
SWTRPROCMGTUTILS_TARFILE_NAME   = ${SWTRPROCMGTUTILS_CURPKG}-${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}.${SWTRPROCMGTUTILS_PRIVATE_BUILD_ID}.${SWTRPROCMGTUTILS_BUILD_NUMBER}.tar.gz

SWTRPROCMGTUTILS_SRCDIR_NAME   = ${SWTRPROCMGTUTILS_CURPKG}-${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}.${SWTRPROCMGTUTILS_PRIVATE_BUILD_ID}.${SWTRPROCMGTUTILS_BUILD_NUMBER}


SWTRPROCMGTUTILS_ARCHLINUX_BUILDDIRS = sources srcpackages packages logs

SWTRCOMMON_FILES          = CMakeLists.txt Description.txt Makefile_packages Makefile_doc
SWTRPROCMGTUTILS_DOC_FILES	  =
SWTRPROCMGTUTILS_LICENSE_FILES  = ../../../LICENSE
SWTRPROCMGTUTILS_FILES          = make_swtrprocmgtutils_archlinux.mk
SWTRPROCMGTUTILS_DIRS           = src_c src_demo_c
SWTRSTRLIBUTILS_DIRS            = swtrstrlib

SWTRPROCMGUTILS_CHANGE_LOG = ChangeLog_archlinux

swtrprocmgtutils_all:
		@echo "dummy_all"
		@exit 0;

swtrprocmgtutils_create_distro: swtrprocmgtutils_create_buildarea swtrprocmgtutils_create_changelog swtrprocmgtutils_create_src swtrprocmgtutils_create_pkg

swtrprocmgtutils_create_buildarea:
	@if ! test -d ${PACMANBUILD_BASE}; then \
	       $(foreach item,${SWTRPROCMGTUTILS_ARCHLINUX_BUILDDIRS}, mkdir -p ${PACMANBUILD_BASE}/${item};) \
	fi;

swtrprocmgtutils_create_src: swtrprocmgtutils_create_buildarea
	@echo "Creating Source Distribution ${SWTRPROCMGTUTILS_TARFILE_NAME}";
	@if test -d "${SWTRPROCMGTUTILS_CURPKG}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; then \
	   rm -r -f "${SWTRPROCMGTUTILS_CURPKG}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; \
	fi;
	@mkdir -p "${SWTRPROCMGTUTILS_SRCDIR_NAME}";
	@$(foreach item, ${SWTRCOMMON_FILES} ${SWTRPROCMGTUTILS_FILES} ${SWTRPROCMGTUTILS_DOC_FILES} ${SWTRPROCMGTUTILS_LICENSE_FILES},cp -p ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@$(foreach item, ${SWTRPROCMGTUTILS_DIRS}, cp -r ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@if test -d "${SWTRPROCMGTUTILS_CURPKG}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; then \
	   rm -r -f "${SWTRPROCMGTUTILS_CURPKG}.${SWTRPROCMGTUTILS_MAJOR}.${SWTRPROCMGTUTILS_MINOR}.${SWTRPROCMGTUTILS_SUBVERSION}"; \
	fi;
	@mkdir -p "${SWTRPROCMGTUTILS_SRCDIR_NAME}";
	@$(foreach item, ${SWTRCOMMON_FILES} ${SWTRPROCMGTUTILS_FILES} ${SWTRPROCMGTUTILS_DOC_FILES},cp -p ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	@$(foreach item, ${SWTRPROCMGTUTILS_DIRS}, cp -r ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	pwd;
	$(foreach item, ${SWTRSTRLIBUTILS_DIRS}, cp -r ${item} ${SWTRPROCMGTUTILS_SRCDIR_NAME};)
	ls ${SWTRPROCMGTUTILS_SRCDIR_NAME};
	@mkdir -p "${SWTRPROCMGTUTILS_SRCDIR_NAME}";
	@if ! test -d ${ARCLINUX_SOURCE_DIR}; then \
	   echo "Creating ${ARCLINUX_SOURCE_DIR}"; \
	   mkdir -p ${ARCLINUX_SOURCE_DIR}; \
	fi;
	@tar -czf ${ARCLINUX_SOURCE_DIR}/${SWTRPROCMGTUTILS_TARFILE_NAME} "${SWTRPROCMGTUTILS_SRCDIR_NAME}"
	@rm -r -f "${SWTRPROCMGTUTILS_SRCDIR_NAME}";

swtrprocmgtutils_create_changelog:
			cp ${SWTRPROCMGUTILS_CHANGE_LOG} ${PACMANBUILD_BASE}/ChangeLog

swtrprocmgtutils_create_pkg: swtrprocmgtutils_create_buildarea swtrprocmgtutils_create_changelog
		@cp archpkg_templates/PKGBUILD_${SWTRPROCMGTUTILS_CURPKG}.proto ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XMAJOR/${SWTRPROCMGTUTILS_MAJOR}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XMINOR/${SWTRPROCMGTUTILS_MINOR}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XSUBVERSION/${SWTRPROCMGTUTILS_SUBVERSION}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XPRIVATE_BUILD_ID/${SWTRPROCMGTUTILS_PRIVATE_BUILD_ID}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@sed -i -e "s/XBUILD_NUMBER/${SWTRPROCMGTUTILS_BUILD_NUMBER}/g" ${PACMANBUILD_BASE}/PKGBUILD;
		@if ! test -d ${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}; then \
		   rm -f ${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}/${SWTRPROCMGTUTILS_CURPKG}*.tar.xz; \
		fi;
		@echo "Update checksums";
		@export PKGDEST="${PACMANBUILD_BASE}/${ARCLINUX_PACKAGE_DIR}"; \
		export BUILDDIR="${PACMANBUILD_BASE}"; \
		export SRCDEST="${PACMANBUILD_BASE}/sources"; \
		export SRCPKGDEST="${PACMANBUILD_BASE}/srcpackages"; \
		export LOGDEST="${PACMANBUILD_BASE}/logs"; \
		export PACKAGER="Eric Bruno <eric@ebruno.org>"; \
		cd ${PACMANBUILD_BASE}; \
		echo "--- Working Directory"; \
		pwd; \
		makepkg -g >> ${PACMANBUILD_BASE}/PKGBUILD; \
		export BUILDDIR="${PACMANBUILD_BASE}"; \
		export SRCDEST="${PACMANBUILD_BASE}/sources"; \
		export SRCPKGDEST="${PACMANBUILD_BASE}/srcpackages"; \
		export LOGDEST="${PACMANBUILD_BASE}/logs"; \
		export PACKAGER="Eric Bruno <eric@ebruno.org>"; \
		makepkg -C ${SWTRPROCMGTUTILS_PACMAN_OVERRIDE} updpkgsums;

update_version:
	@echo "Updating Version to $(MAJOR).$(MINOR).$(SUBVERSION).$(PRIVATE_BUILD_ID).$(BUILD_NUM)";
	@if [ -n "$(BUILD_ID)" ]; then \
	   printf "MAJOR = %d\nMINOR = %d\nSUBVERSION = %d\nPRIVATE_BUILD_ID=%d\nBUILD_ID = %d\n" $(MAJOR) $(MINOR) $(SUBVERSION) $(PRIVATE_BUILD_ID) $(BUILD_NUM) > $(VERSION_FILE); \
	else \
	   printf "MAJOR = %d\nMINOR = %d\nSUBVERSION = %d\nPRIVATE_BUILD_ID=%d\nBUILD_ID = %d\n" $(MAJOR) $(MINOR) $(SUBVERSION) $(PRIVATE_BUILD_ID) 0 > $(VERSION_FILE); \
	fi;
