Document: swtrstrlib
Title: Debian swtrstrlib Manual
Author: <insert document author here>
Abstract: This manual describes what swtrstrlib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/swtrstrlib/swtrstrlib.sgml.gz

Format: postscript
Files: /usr/share/doc/swtrstrlib/swtrstrlib.ps.gz

Format: text
Files: /usr/share/doc/swtrstrlib/swtrstrlib.text.gz

Format: HTML
Index: /usr/share/doc/swtrstrlib/html/index.html
Files: /usr/share/doc/swtrstrlib/html/*.html
