name: OS Tools Sanity

on:
  push:
    branches:
      - '**'
    paths:
      - ./**/Makefile
      - spec/**/*_spec.sh
      - lib/**/*.sh
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: debian
    steps:
      - name: Check env
        run: env;
  sanity:
    runs-on: debian
    steps:
      - name: system management sanity
        uses: actions/checkout@v4
        run: |
          make -C system_management sanity_all;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: junit reports
          path: ./**/report/*.xml

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v4 #Github built in action
        if: always()
        with:
          report_paths: ./**/report/*.xml
